"""Exercício 02 aula 04: Inclusão de coluna 'updated_at' na tabela 'users'

Revision ID: 3e669ffa8d12
Revises: 39de923dfd43
Create Date: 2025-12-12 14:23:01.727796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e669ffa8d12'
down_revision: Union[str, Sequence[str], None] = '39de923dfd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
